# Generated by Django 5.1.4 on 2025-01-08 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('songs', '0002_alter_song_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='record',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.artist'),
        ),
    ]
